[package]
name = "rust_cracking_the_coding_interview"
version = "0.1.0"
authors = ["vsramanujan <rama.psbb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
